### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by Norhua** [cmarky/tianruo-ocr_Fix#1]
老哥这该怎么用啊

**Comment by cmarky** [comment]
啊，编译一下就可以了啊

姜重阳
***@***.***

签名由 网易灵犀办公 定制




在2021-10-05，Amadeus ***@***.***> 写道:-----原始邮件-----
发件人： Amadeus ***@***.***>
发件时间: 2021年10月05日 星期二
收件人： [cmarky/tianruo-ocr_Fix ***@***.***>]
主题： [cmarky/tianruo-ocr_Fix] 不会用 (#1)


老哥这该怎么用啊
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Norhua** [comment]
有编译好的版本吗（

**Comment by cmarky** [comment]
我在releases发了个包，你看看可以用吗！

> 有编译好的版本吗（

我在releases发了个包，你看看可以用吗！

**Comment by Norhua** [comment]
好了。十分感谢！！这段时间被utools折磨透了，太难用了那玩意。

**Comment by cmarky** [comment]
确实用习惯了！不客气
